package ludot.players;

import ludot.board.GameView;
import ludot.moves.Move;

import java.util.List;

/**
 * Selects one move from the legal list generated by {@code MoveGenerator}
 * (Strategy, DESIGN.md 4.1). Must never inspect or enforce game rules, and
 * must never mutate game state — it can only read through {@link GameView}.
 */
public interface PlayerStrategy {

    Move choose(List<Move> legalMoves, GameView view);
}
